# Generated by Django 4.2.8 on 2024-02-06 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plane', '0002_alter_plane_characteristics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='from')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='created_at')),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plane.plane', verbose_name='Plane')),
            ],
            options={
                'verbose_name': 'Airline',
                'verbose_name_plural': 'Airlines',
            },
        ),
    ]
