# Generated by Django 4.2.8 on 2024-02-07 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plane', '0002_alter_plane_characteristics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('froms', models.CharField(max_length=512, verbose_name='from')),
                ('to', models.CharField(max_length=512, verbose_name='characteristics')),
                ('price', models.PositiveBigIntegerField(default=0, verbose_name='Price of the price')),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plane.plane', verbose_name='Plane')),
            ],
            options={
                'verbose_name': 'Flight',
                'verbose_name_plural': 'Flights',
            },
        ),
    ]
