# Generated by Django 4.2.8 on 2024-02-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='name')),
                ('characteristics', models.CharField(max_length=512, verbose_name='characteristics')),
                ('capacity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Capacity of the plane')),
            ],
            options={
                'verbose_name': 'Plane',
                'verbose_name_plural': 'Planes',
            },
        ),
    ]
